name: anime_world
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  go_router: ^14.6.0
  http: ^1.2.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Spicy-Rice
      fonts:
        - asset: assets/fonts/SpicyRice.ttf
    - family: PatuaOne
      fonts:
        - asset: assets/fonts/PatuaOne.ttf
  